name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_TAG: ghcr.io/$GITHUB_REPOSITORY:pr-${{ github.event.pull_request.number }}

jobs:

  build_push_docker_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --file .github/workflows/Dockerfile --tag ${{ env.DOCKER_TAG }} .

    - name: Login to GitHub container registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image to GitHub container registry
      run: docker push ${{ env.DOCKER_TAG }}

    - name: Post testing instructions as comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          This comment was written by a bot!
