name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:

  build_push_docker_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --tag ghcr.io/$GITHUB_REPOSITORY:${{ env.PR_NUMBER }} .

    - name: Push the Docker image to GitHub container registry
      run: docker push ghcr.io/$GITHUB_REPOSITORY:${{ env.PR_NUMBER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
